# Prometheus Alerting Rules for FamilyFinance

groups:
  - name: family-finance-alerts
    rules:
      # API Health Alerts
      - alert: APIHighErrorRate
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m]))
          / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

      - alert: APIHighLatency
        expr: |
          histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is {{ $value }}s (threshold: 1s)"

      - alert: APIDown
        expr: up{job="family-finance-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "FamilyFinance API is down"
          description: "The API has been unreachable for more than 1 minute"

      # Resource Alerts
      - alert: HighMemoryUsage
        expr: |
          process_resident_memory_bytes{job="family-finance-api"} > 450 * 1024 * 1024
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanize1024 }}B (threshold: 450MB)"

      - alert: CriticalMemoryUsage
        expr: |
          process_resident_memory_bytes{job="family-finance-api"} > 500 * 1024 * 1024
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical memory usage"
          description: "Memory usage is {{ $value | humanize1024 }}B (limit: 512MB)"

      # Database Alerts
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          pg_stat_activity_count{datname="familyfinance"} > 12
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Active connections: {{ $value }} (pool size: 15)"

      - alert: DatabaseSlowQueries
        expr: |
          histogram_quantile(0.95, sum(rate(db_operation_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile query time is {{ $value }}s"

      - alert: PostgresDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been unreachable for more than 1 minute"

      # Traefik Alerts
      - alert: TraefikHighRequestRate
        expr: |
          sum(rate(traefik_entrypoint_requests_total[5m])) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request rate"
          description: "Request rate is {{ $value }}/s"

      - alert: TraefikHighErrorRate
        expr: |
          sum(rate(traefik_entrypoint_requests_total{code=~"5.."}[5m]))
          / sum(rate(traefik_entrypoint_requests_total[5m])) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate at load balancer"
          description: "Error rate is {{ $value | humanizePercentage }}"

  - name: infrastructure-alerts
    rules:
      # Container Alerts
      - alert: ContainerHighCPU
        expr: |
          sum(rate(container_cpu_usage_seconds_total{name=~"family-finance.*"}[5m])) by (name) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} has high CPU usage"
          description: "CPU usage is {{ $value | humanizePercentage }}"

      - alert: ContainerHighMemory
        expr: |
          container_memory_usage_bytes{name=~"family-finance.*"}
          / container_spec_memory_limit_bytes{name=~"family-finance.*"} > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} has high memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} of limit"

      - alert: ContainerRestarting
        expr: |
          increase(container_restart_count{name=~"family-finance.*"}[1h]) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} is restarting frequently"
          description: "{{ $value }} restarts in the last hour"

      # Disk Alerts
      - alert: DiskSpaceLow
        expr: |
          (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Available disk space is {{ $value | humanizePercentage }}"

      - alert: DiskSpaceCritical
        expr: |
          (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical disk space"
          description: "Available disk space is {{ $value | humanizePercentage }}"
